### ISSUE TITLE
Come up with and implement a name for the app

### ISSUE THREAD

**Issue by ionparticle** [ubc/acj-versus#10]
Yeah, we need a name

**Comment by lenglund** [comment]
More ideas:
Answer Pair Improvement Tool (APIT)
Relative Answer Feedback Tool (RAFT)
Relative Evaluation Feedback System (REFS)
Paired Answer Reflection Tool (PART)
Paired Answer Peer Instruction (PAPI)
Paired Answer Comparison Tutor (PACT)
Paired Answer Instruction & Reflection (PAIR)
Paired Answer Reflection Exercise/Engine/Experience (PARE)
Paired Answer Feedback Tool (PAFT)

PairWise
PairUp

**Comment by lenglund** [comment]
More suggestions from the ACJ team:

something that works with RANK could be nice…
Rank Answers … Comparisons (so RANC)
Arr! (Answer, Rank, Reflect)
Acer (Answer Compare Evaluate Reflect)

Compair
Compeer 
Peer Up 
Peer Pick (Pick Peer)
PeerPickles
Peermash (an homage to Facemash)
Pairmash
Peerbook
Judgy Judgments 
Ack!

**Comment by lenglund** [comment]
ACJ group voting resulted in Compair as overall winner (runner-up: ACER).

**Comment by lenglund** [comment]
Updated to Compair in d61773d4e3d7c1aa7c9618ee1abd331bda1c1ad3.
