### ISSUE TITLE
Determine support and do testing

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#110]
What browsers/platforms/devices do we plan to support? These still need to be tested, especially IE.

**Comment by xcompass** [comment]
I would say we align with angularjs browser support, e.g. Safari, Chrome, Firefox, Opera 15, IE9 and mobile browsers (Android, Chrome Mobile, iOS Safari). https://docs.angularjs.org/misc/faq

**Comment by lenglund** [comment]
Testing of display/responsiveness (mostly) completed now for:
Firefox 35.0 (Mac OS X)
Chrome 39.0.2171.95 (Mac OS X)
Safari 7.1.2 (Mac OS X)
Opera 26.0 (Mac OS X)

IE testing to follow. Which version(s) of Windows should I use? 7 and 8?

**Comment by ionparticle** [comment]
Both. I was able to confirm that the current build works fine in IE11 Windows 8 but fails with IE11 Windows 7.

**Comment by mwytang** [comment]
It breaks for IE10 on Windows 8 but works for IE11 on Windows 8.1.

**Comment by lenglund** [comment]
Windows 7 testing completed now for IE9, IE10, and IE11.

**Comment by lenglund** [comment]
iOS Safari tested on iPad.

**Comment by lenglund** [comment]
Closing again after a3363ff95bf383696582c099cb19daf8ff8eaf9b.
