### ISSUE TITLE
Application seems slow

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#115]
A few student users noted the application seems slow to load some pages (e.g., Question screen) and lags when logging in (to the dev site).

**Comment by mwytang** [comment]
Manage Users screen also lags - eg. class of ~130 users

**Comment by mwytang** [comment]
May be able to improve efficiency by implementing #198

**Comment by lenglund** [comment]
Teaching assistants and some students in the piloting courses found the application notably slow. This significantly slowed down the workflow for TAs.

**Comment by lenglund** [comment]
Try removing avatar and see if that improves anything.

**Comment by xcompass** [comment]
It is because there are so many queries on each api call. That's also the reason why marshal is so slow. I'm working on it to reduce the queries.

**Comment by xcompass** [comment]
Made some performance improvements, reduced the amount of queries generated and some clean up. Now the bottleneck is that some of the API calls returns large data set when there are more students. E.g. answer list API and comparison API. The data was converted from database rows into objects and marshalled into json, which takes a lot of time. 

The proposed solution is to load the data in batch (pagination). E.g. for answer list, load only a few at the beginning and when user needs more, loads more. Also loading the comments for answer as a separated call. This requires pagination support from backend API.

**Comment by lenglund** [comment]
Pagination issue completed in 5ce680be9871e058bf51f2ee7cbc430c424d4791.
