### ISSUE TITLE
Add transaction to the migration scripts

### ISSUE THREAD

**Issue by xcompass** [ubc/acj-versus#167]
When migrating the database, the alembic uses non-transactional DDL. e.g.:

    INFO  [alembic.migration] Will assume non-transactional DDL.

**Comment by mwytang** [comment]
alembic does not do this by default because MySQL cannot handle it. For more information: http://dev.mysql.com/doc/refman/5.0/en/cannot-roll-back.html

**Comment by xcompass** [comment]
Thanks.
