### ISSUE TITLE
Allow instructors to edit users?

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#171]
Decide what editing ability instructors should have in the system, considering that they can create users and may need to edit/correct user information.

**Comment by mwytang** [comment]
Right now, instructors can update parts of the user profile for their students via the class import feature. The fields include the following: student number, first name, last name, email, and display name. Should we restrict this if instructors cannot do the same thing via the interface?

**Comment by lenglund** [comment]
I think it makes sense that these would match up.

**Comment by lenglund** [comment]
Instructors will be given edit ability going forward. This means re-enabling the "Edit" button on the profile screen (when the instructor is allowed to edit that user's profile, i.e., the student is enrolled in one of the instructor's courses) and adding "Edit" links in the manage users table.
