### ISSUE TITLE
Fix manage database bug

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#175]
When we run the following command, the database is dropped, created, and populated successfully.

`python manage.py database recreate -s`

However, when we break up the commands within the command above, we get an integrity error when we try to populate the database with sample data. The commands are the following, and the error occurs when the last command is run.

`python manage.py database drop`
`python manage.py database create`
`python manage.py database populate -s`

`sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) (1048, u"Column 'criteria_id' cannot be null") 'INSERT INTO `CriteriaAndCourses` (criteria_id, courses_id, active) VALUES (%s, %s, %s)' (None, 1, 1)`

When I tried to hard code the criteria_id as 1 for both CriteriaAndCourses and CriteriaAndPostsForQuestions. We also have the problem that all the students are given Instructor System Role and all users given Instructor Course Role for all Courses.

**Comment by mwytang** [comment]
A possible reason is when we are populating the database with sample data, we are also using the DefaultFixture we have just created. However, the "DefaultFixture" variables no longer hold valid values; it now has "None". I believe this is because the DefaultFixture and SampleDataFixture are being created in different scopes. 

When we do everything with one command, they are all in the same scope, therefore SampleDataFixture will have valid DefaultFixture values.

**Comment by mwytang** [comment]
@ionparticle, is this solution alright?

**Comment by xcompass** [comment]
It seems work correctly on my local mysql and sqlite.

**Comment by ionparticle** [comment]
Yep, confirm fixed.

**Comment by xcompass** [comment]
Who fixed it?

**Comment by mwytang** [comment]
@xcompass, it was fixed in commit 63ed142dfbbc64b7cdfccc37d5560cde0ec8049c.
