### ISSUE TITLE
Rename models to match their respective database table names

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#178]
Recently, we have renamed some of the database tables and their related foreign key columns and foreign key constraints so that we can continue to use the convention but not have names that are too long (maximum 64 characters).

We have not changed the names in the related class models yet. By changing the class model names, it would be more convenient for us when we try to refer to the database or model in the backend. This change will however require lots of changes in the backend, which includes the backend tests, API, factories, etc.

**Comment by lenglund** [comment]
Part of #266.

**Comment by andrew-gardener** [comment]
Fixed #297
