### ISSUE TITLE
Make user's display name not required to be unique

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#180]
- If we make the display name unique, it will slow down class import
- For an instructor, it would not matter since they can see the real names of the students

**Comment by mwytang** [comment]
completed in commit 0fa104084606d774e5300166ede47d36e42e4ccb.

**Comment by mwytang** [comment]
Update the Import Users text

**Comment by lenglund** [comment]
Text updated in a6bad5fefa0cee85cc18278f0263d8878e506e31
