### ISSUE TITLE
Refactor classlist import

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#181]
It takes a couple of minutes to import a class of about 150-160 users. This needs to be refactored to be faster, because we are expecting class sizes of about 500 to 1000 in the future (eg. combined courses).

**Comment by mwytang** [comment]
Possible Solutions
- has passwords as a background task
- skip reassigning passwords to existing users
- not update existing users - eg. if a user changed their First Name to the preferred name, this will be overwritten each time we update the roster.

**Comment by mwytang** [comment]
- [ ] may be a good idea to have user feedback

**Comment by lenglund** [comment]
Need to do some testing to determine how much of a problem this is.
