### ISSUE TITLE
Printing Question and Evaluation Results Screen bug

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#183]
When I print, some of the links have a mysterious "()" at the end. For example:

4 replies to this answer (4 private, 0 public)

will be printed as

4 replies to this answer (4 private, 0 public) ()

**Comment by lenglund** [comment]
I've noticed this, too, and could not find a solution when I looked into it a few months ago. Anyone have ideas what would cause this to happen?

**Comment by mwytang** [comment]
I think it has to do with the empty href attribute. When I assign '#' to the href attribute, the extra brackets are gone. However the application redirects us to the home page. I've found some possible solutions at http://stackoverflow.com/questions/22940761/best-way-to-create-an-a-link-with-empty-href . I haven't tested them though

**Comment by lenglund** [comment]
Thanks, this helped me find the style that Bootstrap was using and overwrite it. This should be fixed as of 17e4148584b7a5b2455e8c49e719921f8c4df88c.
