### ISSUE TITLE
User creation - auto generate password

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#184]
It may be a good idea to change the password to be auto-generated. Currently, only instructors and admins can create users, which means the "user creation" feature is mostly used for creating accounts for other people. It may be hard to come up with good temporary passwords on the spot. It is probably easier to have the password auto-generated and have the user copy down the password.

**Comment by lenglund** [comment]
I would actually argue for the reverse. It's easier for a person to create a password they can remember. Although the issue there is that the password will most likely be a weak one...

**Comment by lenglund** [comment]
I think we decided against this because of the complexity in retrieving lost passwords?
