### ISSUE TITLE
Timezone adjustments

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#187]
- Will affect the warning timers, deadlines, answer and evaluation periods
- Account for common practices for Distance Education courses

**Comment by mwytang** [comment]
- [] API to get server time for time adjustments on the front-end

**Comment by mwytang** [comment]
Moment.js formats the UTC time given by the server to the timezone set on the user's computer. Therefore visually, the deadlines will be adjusted accordingly.

**Comment by ionparticle** [comment]
Tested that moment.js takes care of this automatically. Time is stored in database as utc too.
