### ISSUE TITLE
Revamp Criteria Backend Structure

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#189]
Do we want to refactor the Criteria backend structure. For example, instead of having criteria relating to the course first before relating them to the questions, we can instead relate criteria directly to questions. This will allow criteria to be editable (copy and modify as new) even after they have been used.

**Comment by lenglund** [comment]
If this opens up a new way for criteria to be added/edited/deleted, it may be beneficial from the instructor POV. Not all instructors found the current managing of criteria to be intuitive.

**Comment by lenglund** [comment]
Changes to how UI works makes managing criteria easier now. This approach may no longer be needed.

**Comment by lenglund** [comment]
Reopening for discussion.

**Comment by andrew-gardener** [comment]
#297 Criteria are now managed at the assignment level. 

This change does not allow editing already compared criteria though (copy and create new on 'edit'). Is this still desired?

**Comment by xcompass** [comment]
Why is this restriction?

**Comment by lenglund** [comment]
The concern in the past has been that if a criterion is changed, it potentially changes the context of the comparisons done with that criterion previously. So prior comparisons should either retain the previous version of the criterion  (this would be preferred, I think, in terms of UX) or the criterion should not be editable.

**Comment by xcompass** [comment]
can we allow minor updates? e.g. fixing typos ,etc.

**Comment by andrew-gardener** [comment]
We could put a warning message when editing compared criteria and trust them to not make serious changes but I can't think of a feasible way to allow only minor updates.

**Comment by lenglund** [comment]
I like Andrew's suggestion, as otherwise we might have to introduce a "minor edit" checkbox that is just one more thing for instructors to process on the form. 

Might be a question to run by Ido too, as I think the concern pertains more to doing research/analysis on the outcomes vs. the instructors wanting to preserve the criterion themselves.

**Comment by xcompass** [comment]
I'm OK with the warning message.

**Comment by andrew-gardener** [comment]
Tasks to close issue:
- [x] Move criteria management from course to assignment
- [ ] Allow editing compared criteria
- [ ] Add warning message when editing compared criteria
