### ISSUE TITLE
Is caching the main problem with Internet Explorer?

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#197]
In starting to log all the issues with IE9, I'm seeing a clear pattern develop. Most of the bugs are happening because IE is using cached data instead of the most recent data. I'm not familiar with configuring this aspect of Angular, so perhaps someone else can weigh in. Could this be the issue: http://www.oodlestechnologies.com/blogs/AngularJS-caching-issue-for-Internet-Explorer?

**Comment by mwytang** [comment]
Try: https://github.com/saintmac/angular-cache-buster

**Comment by mwytang** [comment]
IE seems to work with angular-cache-buster. Now we just have to configure it correctly - eg. continue to cache html and css files

**Comment by lenglund** [comment]
This appears to have fixed the main issues with logging in, doing comparisons, updating statuses, and editing. Yay.

**Comment by mwytang** [comment]
I have found some minor caching problems. To reproduce the problem:

- login as `instructor1`
- go into a course - notice the instructor still has the option to submit an answer
- logout
- login as `student1`
- go to the sam course - notice the option to submit an answer is still available, even though this particular student has already submitted an answer.
