### ISSUE TITLE
enable $http cache for frontend

### ISSUE THREAD

**Issue by xcompass** [ubc/acj-versus#198]
By enabling angulerjs $http cache, we can reduce a lot of duplicate API calls. Thus improve performance.

**Comment by mwytang** [comment]
Have to make sure all the cached API calls are cleared at logout so that  we do not carry over the data to another user who may login with the same computer.

**Comment by mwytang** [comment]
- Implemented cache for:
    - course - invalidate after editing or deleting a course
    - evaluation comments
    - question - invalidate after editing or deleting question
    - answer - invalidate after editing, deleting, or flagging
    - classlist - invalidate after un/enroling user, update group enrolment, class import, or group import
