### ISSUE TITLE
Identical Session ID bug

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#202]
When two different users log in with the same browser on the same computer, they both get the same session id.

**Comment by xcompass** [comment]
The way flask-login generate the session ID is using md5 of user's IP and browser agent. Therefore, the session ID could be the same if those two parameters are the same. Flask also stores session data on the client side. Unless the cookie is stolen from the user, it is considered to be safe.

With commit 776e5d5, session will expires in 1 day instead default 31 days to make it more secure. A session token is added to identify user login sessions. E.g. every time user logs in, it generate a new token. This token is being used in the activity log.
