### ISSUE TITLE
IE9/IE10: Inline PDF viewer does not work

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#204]
When a user clicks the "Show PDF" button, the inline PDF viewer tries to open but is blank. The toolbar buttons are also disabled in IE9, so the user is not able to download the PDF either. In IE10, the user can at least do the download to view the PDF.

**Comment by mwytang** [comment]
@ionparticle, has fixed it by commit 517633ef89e68541b4222f1babaa07b7e2ed75aa.

**Comment by lenglund** [comment]
Is it possible this would fix display issues with the viewer in iOS Safari as well? I'm encountering the same issue on the iPad, but I am testing on the dev site...

**Comment by ionparticle** [comment]
It should. Dev site wasn't updated with this patch. Note though, pdf.js marks Safari support as "limited", so while pdfs should render, they might not be rendered correctly always.

**Comment by mwytang** [comment]
It looks like it works fine.

![image](https://cloud.githubusercontent.com/assets/1680669/6253518/d6f89c54-b756-11e4-92b8-0c51e9a5a0be.jpg)
