### ISSUE TITLE
Latex module pop up every time

### ISSUE THREAD

**Issue by xcompass** [ubc/acj-versus#207]
From Mark:
> Also, the example in the latex module is good, but it would be nice to be able to not have it pop up every > time....gets a bit irritating to clear it.

**Comment by lenglund** [comment]
I'm not sure there is a strong enough case here for removing the default example. If I understand correctly, most students are not going to be entering multiple answers in one session (as Mark is possibly doing to test the system). So the example may actually be useful each time, particularly if the user is not experienced enough to know the syntax off-hand and the assignments are spread out.

I can see the use in removing this for advanced users, but not novice or casual ones...

**Comment by ionparticle** [comment]
Would having a "Load Example" button instead be an acceptable compromise?

**Comment by xcompass** [comment]
I think so.

Cheers,
Pan
