### ISSUE TITLE
Delete does not immediately remove answers / replies from front end

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#209]
Answers and replies ARE deleted from the back end, but the change only appears on the front end once the page is refreshed. Otherwise, it appears that the answer or reply has NOT been deleted (although a success message does confirm the deletion). 

Sometimes, another answer or reply looks like it is deleted (because it is removed from the front end when clicking delete for another item), but it reappears after the refresh (and the selected answer or reply is gone instead, as expected).

This probably has to do with using filters with the ng-repeat index to target the item for deleting...

What does work as expected:
- Deleting questions from the course screen
- Deleting comments from the question screen

What does not work:
- Deleting answers from the question screen
- Deleting replies (public or private) from the question screen

**Comment by mwytang** [comment]
last commit for the fix is 442c06b2dab73b799b184202ff34babde20a2f32
