### ISSUE TITLE
Remove unique displayname constraint failed on dev

### ISSUE THREAD

**Issue by ionparticle** [ubc/acj-versus#211]
Looks like the constraint on dev was just named 'displayname'.

Was able to bypass using this query:
    DROP INDEX displayname ON Users;

The upgrade script should be modified to check to either check if the constraint exists before removing it or to try this alternate method if the exisiting one fails.

Will need this before we try upgrading prod.

**Comment by mwytang** [comment]
I'm sorry. I forgot to mention that we have to alter the name of the index so that it complies with the convention. The script to run in the MySQL terminal is:

        ALTER TABLE Users
	        DROP INDEX displayname,
	        ADD CONSTRAINT uq_Users_displayname UNIQUE (displayname);

Then run the database upgrade script. We need to complete #178 soon to prevent this problem occurring again.

**Comment by mwytang** [comment]
Fixed. Permanent solution is #214.
