### ISSUE TITLE
Tests seem to fail in Travis from time to time

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#220]
The tests seem to fail (mostly acceptance tests - and not all jobs fail) in Travis from time to time even though the tests pass locally. This may be due to some race conditions. If it is a race condition problem, we may want to try reducing the number of concurrent jobs. This can done by following the instructions found at http://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/.

Another reason I believe it may be a race condition problem is the tests passes when I run the jobs one at a time.

**Comment by lenglund** [comment]
Seems pretty consistent.
