### ISSUE TITLE
Token Authentication

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#221]
This authentication method allows us to easily timeout people's access to the backend since the token will have an expiry date. Also it will fix #202, since tokens generation is dependent from the browser and IP the user is using. This resource (http://blog.miguelgrinberg.com/post/restful-authentication-with-flask) may be useful for implementing it.

**Comment by lenglund** [comment]
Duplicate of #249.

**Comment by lenglund** [comment]
Closing due to duplication.
