### ISSUE TITLE
Provide better access and instructions to class list management

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#222]
Instructors had to contact CTLT to update their class lists for the piloting courses. It would be easier going forward if the lists updated automatically or instructors could make changes in a simple way (not CSV files, as this is too challenging to obtain) themselves.

**Comment by lenglund** [comment]
Adding an option to export a CSV of the existing class list could help, as proposed in #114.

**Comment by xcompass** [comment]
Exporting classlist feature has been implemented in bc9994e6923cda0edf9f8d88f0111619e5a54a23.

We may also implement LTI and integration with SIS. Lowering the priority for now.
