### ISSUE TITLE
No place to test application

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#224]
Instructors don't have an area for testing how questions look and work. A sandbox area for this kind of experimenting would be useful in getting familiar with the application.

**Comment by xcompass** [comment]
sandbox is at http://acj.ctlt.ubc.ca

**Comment by lenglund** [comment]
I think the request was more to have a place they can log in without having to have someone set things up for them first. But if we are willing to provide this support, then I think this is fine.

**Comment by xcompass** [comment]
What kind of setup? The instructor/students usernames and passwords were sent around. So we can share those to who ever want to try it out.
