### ISSUE TITLE
Allow instructors/TAs to give private feedback to students

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#228]
Teaching assistants can't give private feedback to students on their answers or replies, since all replies using the "Reply" button are public. This forced any TA from a piloting course wishing to give private feedback to do so outside the application.

Allow instructors and teaching assistants to choose between "Public" or "Private" when replying in the application.

**Comment by lenglund** [comment]
Checkbox defaults to private, check if you want it to be public.

**Comment by mwytang** [comment]
The feature is now functional. Some textual changes is still needed on the question screen

**Comment by lenglund** [comment]
Completed in 74da164ed3fc0507b0026c3b06907f210941a45f. Private/public replies available to all users when replies are enabled for an assignment. Private/public replies available to instructors/TAs only when replies are disabled for an assignment.
