### ISSUE TITLE
PDF upload not working consistently?

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#233]
Some students could not get the PDF upload to work when submitting answers for the piloting math course. Test the PDF upload on more browsers/platforms.

**Comment by lenglund** [comment]
Consider making instructional text larger to account for user errors, e.g., file type and size restriction?

**Comment by mwytang** [comment]
We can simulate slow connection

**Comment by mwytang** [comment]
- tested uploading large pdf - get the appropriate error message that the file is too large

**Comment by lenglund** [comment]
Problems noted with testing in IE:
In IE9 (Win7)—PDF file from desktop would seem to complete uploading but report "0.0" for file size and file would not ultimately save (happened with any PDF file).
In IE10 (Win8) / IE11 (Win8.1)—error appears saying file is wrong type (none were) until I installed Acrobat Reader. Then works as expected.

**Comment by lenglund** [comment]
Added note for file size maximum and tip for downloading Acrobat Reader in 567db58d6e76d04d486cd2c72a1546dfefc65e01.

**Comment by lenglund** [comment]
As problems do not have obvious solutions at this time, I am going to close the issue and we'll see if the instructional text is enough to help with future uploading issues. If problems persist, we can look at other solutions (e.g., another uploader)...

**Comment by lenglund** [comment]
Logic for uploader input and messages updated in e037403edd97fc12f9c6be9b0fc73fc8b58b0f42.
