### ISSUE TITLE
PDF viewer creates confusion?

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#234]
Displaying PDFs during comparisons did not work as expected. The drawings submitted for the math class were too small for the inline viewer. Students could not easily figure out an alternative to the inline display that would allow them to view a larger version of each answer file.

Check how these files look and consider providing an alternate way to view the PDFs (e.g., a link opening the file in a new tab/window).

**Comment by lenglund** [comment]
Consider adding a "Download PDF" button next to the existing "Show PDF" button.

**Comment by mwytang** [comment]
I have implemented the "Show PDF" as an overlay, but can't seem to enlarge the overlay without affecting the login overlay

**Comment by lenglund** [comment]
Should be noted that the current PDF viewer does allow for both zooming and downloading, if it is working properly in the browser (i.e., the student can click "Show PDF" and the viewer appears).

**Comment by lenglund** [comment]
Issue resolved in e7b41b0c1a5c3e8adf08bee487d1111e6d333795
