### ISSUE TITLE
Ranking of answers not wanted by all students/TAs

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#237]
Some students in the piloting courses wanted answer rankings to not be shown. The preferred approach here would be to only show the top ten (or custom number) answers and the rest in no clear order, to prevent students at or near the bottom from feeling demoralized.

Additionally, TAs in the second English pilot course expressed concerns over the demoralizing effect of a low ranking. They were interested in the application/exercises being presented in more of a "workshop" way, where students come to learn and help one another vs. be evaluated/judged.

Should we consider showing answers by default by date submitted? And provide a "top ten" (or more) option for each criterion in the dropdown that only shows the answers ranked in the top ten? Should we change the way the application and assignments are presented to soften the "judgement" aspect?

**Comment by lenglund** [comment]
Needs to be discussed with #51.

**Comment by lenglund** [comment]
Decision is to have answers shown by submission date/time for students, with the option to view the answers in the top 10-20% (was an exact number decided on here?). Instructors will still see ranking along with percentages.

What needs to happen to resolve this issue then is:
- [ ] Change student default view of answers to sorting by submission date/time (if not done already)
- [ ] Add filter option to view Answers in Top xx% (available for students, TAs, and instructors)
- [ ] Resolve issue #51

**Comment by lenglund** [comment]
@andrew-gardener, can you add a ranking display option to the back end? For now, we'll let instructors choose from three options: to display the top 10 answers, to display the top 20 answers, or to display no ranking. Then I will complete this issue...

**Comment by lenglund** [comment]
Note that display of ranking is dependent on #315. If random is used, ranking is not shown. Form needs to reflect this.

**Comment by andrew-gardener** [comment]
passing back to @lenglund
