### ISSUE TITLE
Website timed out and could not be accessed without clearing cache?

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#239]
A student reported challenges with getting logged out and then not being able to log in again without clearing the browser cache or switching browsers altogether. What would cause this to happen?

**Comment by lenglund** [comment]
Michael will check if there is a session time out. If there is an unexpected default, this could be adjusted.

**Comment by lenglund** [comment]
No session time out was found. Possibly, this is a user error and users reporting the issue are closing the browser and expecting to stay logged in. Could be addressed with additional instructions/labelling in application?

**Comment by xcompass** [comment]
I'm lowering the priority until we found another case. And moving it to later milestone.
