### ISSUE TITLE
More details when documenting user/system actions

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#240]
It would be nice to have:

- a way to tell if the activity/event recorded comes from a user action (eg. clicking a button) or a system action (eg. loading page and grabbing required data)
- a way to tell which page the user was on when the activity/event was launched.

This is mainly for research purposes.

**Comment by scmc** [comment]
Would also be great if those could generate xAPI statements. That fed to the LRS.

**Comment by mwytang** [comment]
Great idea, Scott. We can use #41 to complete this requirement.

**Comment by lenglund** [comment]
To be started in #264.
