### ISSUE TITLE
ACJ doesn't load in Windows 10 Edge

### ISSUE THREAD

**Issue by ionparticle** [ubc/acj-versus#247]
Looks like angular-sanitize fails to load, causing the entire app to fail.

**Comment by lenglund** [comment]
Related at all to message from Kyle/IT? "Just forwarding along a caveat from UBC IT for those of you thinking about upgrading to Windows 10 yourselves.  In summary - they do not recommend the upgrade at this time as some UBC services won't work as of yet - like the UBC VPN."

**Comment by xcompass** [comment]
after updating the libraries. It seems fine now.
