### ISSUE TITLE
Some answer replies not visible to students or TAs

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#253]
Students in the second pilot for the English course reported not being able to see any replies to their own answers. When TAs logged in to confirm, they were not able to see any replies either. The application also shows students and TAs that 0 replies were left for the answer. Yet when an administrator logs in, 1 or more replies have been left and are visible for the answer.

Something is likely wrong with the permissions of the replies. (I can share a student example for the English course offline.)

**Comment by andrew-gardener** [comment]
Could not reproduce in development or production.

It might have been caused by #250
