### ISSUE TITLE
Allow students to save drafts of answers and comparisons

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#258]
For the second pilot in Physics, the issue was once again raised (previously recorded for #231) that students would like to be able to save work as they go vs. only being able to submit at the end.

**Comment by lenglund** [comment]
Look into an auto-save.

**Comment by lenglund** [comment]
Ties into #254.

**Comment by andrew-gardener** [comment]
- [x] Back-end changes comparison drafts (#297)
- [ ] Back-end changes answer drafts
- [ ] UI changes for comparison drafts
- [ ] UI changes for answer drafts

**Comment by lenglund** [comment]
Completed in 86fb95591c73f97600282bce53817de6c63ff795.
