### ISSUE TITLE
LTI integration

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#263]
Integrate application to work within the larger educational technology ecosystem using LTI.

**Comment by jleong-openedx** [comment]
General:
- [ ] display three options (CWL, app-specific, create new account) for a launch request for a user who has never linked their LMS account with a ComPAIR account
- [ ] check for existence of LTI launch request
- [ ] verify validity of LTI launch request
- [ ] check for presence of all required parameters in launch request
- [ ] link user_id, and CWL or app-specific login, and ComPAIR account when the user first logs into ComPAIR or creates a ComPAIR account for an LTI launch request

Students:
- [ ] after account linkage, redirect student to appropriate landing page if LMS course not yet linked to ComPAIR course
- [ ] enroll student in ComPAIR course if not already enrolled, and if course linkage exists, with an appropriate message e.g. "You are now enrolled in this ComPAIR course"
- [ ] redirect student to course page if course linkage exists
- [ ] redirect student to assignment/question page if course linkage exists and custom parameter exists

Instructors:
- [ ] after account linkage, redirect instructor to a page that asks them to choose an existing course, or create a new course to link the context_id to
- [ ] if new course option chosen, redirect to "Add Course" page and link context_id with newly created course when the instructor clicks "Save"
- [ ] if select existing course option chosen, redirect to a "Select Existing Course" page and link context_id with selected course when the instructor clicks "Save"
- [ ] after course linkage, redirect instructor to the appropriate question/assignment page if the appropriate custom parameter exists in the launch request
- [ ] after course linkage, redirect instructor to the appropriate course page if the appropriate custom parameter does not exist in the launch request
- if the user is an instructor, display a custom parameter value on the course page, with a tooltip to instruct the user to configure this in the LTI launch request settings, for directing the launch request to a question/assignment page

**Comment by andrew-gardener** [comment]
Last few tasks: 
- [ ] CWL flow (#335)
- [ ] Last UI elements (#337) 
- [ ] Last back-end unit tests
