### ISSUE TITLE
Continuous integration test issues

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/acj-versus#273]
Currently Travis test 

- [x] Modify Travis script to better manage number of SauceLab connects #278
- [x] Reduce maximum number of Travis jobs to help prevent going over SauceLab's job limit (5)

<s>Investigate why "make deps" step sometimes fails</s>

**Comment by andrew-gardener** [comment]
It seems to run fine when only 2 concurrent jobs are running.
With 3, the one might start to fail with one of the above situtations.

I'll try setting "limit concurrent jobs" to 2 in the Travis CI settings for this repo and see if the issue persists

**Comment by xcompass** [comment]
It seems saucelabs does have 5 concurrent limit.

**Comment by andrew-gardener** [comment]
SauceLabs 1: To many active user tunnels

> ...
Extracting Sauce Connect
Waiting for Sauce Connect readyfile
22 Apr 22:05:44 - Sauce Connect 4.3.14, build 2010 d6099dc
22 Apr 22:05:44 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
22 Apr 22:05:44 - Using CA certificate verify path /etc/ssl/certs.
22 Apr 22:05:44 - Starting up; pid 3668
22 Apr 22:05:44 - Command line arguments: sc-4.3.14-linux//bin/sc -i 616.2 -f sauce-connect-ready-26131 -l /home/travis/sauce-connect.log
22 Apr 22:05:44 - Log file: /home/travis/sauce-connect.log
22 Apr 22:05:44 - Pid file: /tmp/sc_client_616.2.pid
22 Apr 22:05:44 - Using no proxy for connecting to Sauce Labs REST API.
22 Apr 22:05:44 - Resolving saucelabs.com to 162.222.75.243 took 1 ms.
22 Apr 22:05:44 - Started scproxy on port 37974.
22 Apr 22:05:44 - Please wait for 'you may start your tests' to start your tests.
22 Apr 22:05:44 - Starting secure remote tunnel VM...
22 Apr 22:05:45 - POST https://saucelabs.com/rest/v1/compass/tunnels: HTTP response code indicated failure.
22 Apr 22:05:45 - Response: {"error": "Too many active user tunnels: 5 >= 5"}.
22 Apr 22:05:45 - Error creating tunnel.
22 Apr 22:05:45 - Cleaning up.
22 Apr 22:05:45 - Sauce Connect could not establish a connection.
22 Apr 22:05:45 - Please check your firewall and proxy settings.
22 Apr 22:05:45 - You can also use sc --doctor to launch Sauce Connect in diagnostic mode.
22 Apr 22:05:45 - Goodbye.
...

**Comment by andrew-gardener** [comment]
Python Error: Python executable "python" is v3.4.2, which is not supported by gyp.

>...
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/ubc/acj-versus/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
>
> bufferutil@1.2.1 install /home/travis/build/ubc/acj-versus/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild
>
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/ubc/acj-versus/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! cb() never called!
npm ERR! not ok code 0
make: *** [deps] Error 1

**Comment by andrew-gardener** [comment]
SauceLabs 2: One or both selenium instances don't seem to run (example of both not running)

>...
The command "make deps" failed and exited with 2 during .
$ DISABLE_MOCK=false node_modules/.bin/gulp test:ci
[22:38:40] Using gulpfile ~/build/ubc/acj-versus/gulpfile.js
[22:38:40] Starting 'server:frontend'...
[22:38:40] Finished 'server:frontend' after 20 ms
[22:38:40] Starting 'test:ci'...
[22:38:40] Server started http://localhost:8080
[launcher] Running 2 instances of WebDriver
>
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by andrew-gardener** [comment]
Reduced Number of Travis jobs repo uses to 4 to help prevent going over SauceLab's limit

**Comment by andrew-gardener** [comment]
Note: its still possible to go over SauceLab's limit when cancelling Travis jobs with active connections. The SauceLab connections will remain open until they timeout since they are never closed properly.

**Comment by andrew-gardener** [comment]
Possible solution to the occasional make deps error:
call
`npm cache clean `
before
`npm install`

refs: 
http://stackoverflow.com/questions/15393821/npm-err-cb-never-called
https://github.com/npm/npm/issues/2907

**Comment by andrew-gardener** [comment]
Updating Node version might fix the "make deps" step issues

From a test calling `npm cache clean` before `npm install` the step breaks at a different point
https://travis-ci.org/ubc/acj-versus/jobs/128165534

**Comment by tomfun** [comment]
gitlab-**ci**-multi-runner
launched inside docker

I have already done ```npm cache clean```

> $ npm install --loglevel silly --color always
> npm info it worked if it ends with ok
> npm verb cli [ '/usr/local/bin/node',
> npm verb cli   '/usr/local/bin/npm',
> npm verb cli   'install',
> npm verb cli   '--loglevel',
> npm verb cli   'silly',
> npm verb cli   '--color',
> npm verb cli   'always' ]
> npm info using npm@3.7.3
> npm info using node@v5.9.0
> npm sill loadCurrentTree Starting
> npm sill install loadCurrentTree
> npm sill install readLocalPackageData
> npm sill install normalizeTree
> npm sill loadCurrentTree Finishing
> npm sill loadIdealTree Starting
> npm sill install loadIdealTree
> npm sill cloneCurrentTree Starting
> npm sill install cloneCurrentTreeToIdealTree
> npm sill cloneCurrentTree Finishing
> npm sill loadShrinkwrap Starting
> npm sill install loadShrinkwrap
> npm sill loadShrinkwrap Finishing
> npm sill loadAllDepsIntoIdealTree Starting
> npm sill install loadAllDepsIntoIdealTree
> npm sill fetchNamedPackageData twitter_cldr
> npm sill mapToRegistry name twitter_cldr
> npm sill mapToRegistry using default registry
> npm sill mapToRegistry registry https://registry.npmjs.org/
> npm sill mapToRegistry uri https://registry.npmjs.org/twitter_cldr
> npm verb request uri https://registry.npmjs.org/twitter_cldr
> npm verb request no auth needed
> npm info attempt registry request try #1 at 3:12:10 PM
> npm verb request id 204d01c80a59cb84
> npm http request GET https://registry.npmjs.org/twitter_cldr
> npm http 200 https://registry.npmjs.org/twitter_cldr
> npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
> npm verb headers   etag: '"3YKAYH78VF4SY2KUO1BJ53F01"',
> npm verb headers   'content-type': 'application/json',
> npm verb headers   'content-encoding': 'gzip',
> npm verb headers   'cache-control': 'max-age=300',
> npm verb headers   'content-length': '3147',
> npm verb headers   'accept-ranges': 'bytes',
> npm verb headers   date: 'Fri, 13 May 2016 15:12:06 GMT',
> npm verb headers   via: '1.1 varnish',
> npm verb headers   age: '252',
> npm verb headers   connection: 'keep-alive',
> npm verb headers   'x-served-by': 'cache-fra1223-FRA',
> npm verb headers   'x-cache': 'HIT',
> npm verb headers   'x-cache-hits': '1',
> npm verb headers   'x-timer': 'S1463152326.975488,VS0,VE0',
> npm verb headers   vary: 'Accept-Encoding' }
> npm sill get cb [ 200,
> npm sill get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
> npm sill get     etag: '"3YKAYH78VF4SY2KUO1BJ53F01"',
> npm sill get     'content-type': 'application/json',
> npm sill get     'content-encoding': 'gzip',
> npm sill get     'cache-control': 'max-age=300',
> npm sill get     'content-length': '3147',
> npm sill get     'accept-ranges': 'bytes',
> npm sill get     date: 'Fri, 13 May 2016 15:12:06 GMT',
> npm sill get     via: '1.1 varnish',
> npm sill get     age: '252',
> npm sill get     connection: 'keep-alive',
> npm sill get     'x-served-by': 'cache-fra1223-FRA',
> npm sill get     'x-cache': 'HIT',
> npm sill get     'x-cache-hits': '1',
> npm sill get     'x-timer': 'S1463152326.975488,VS0,VE0',
> npm sill get     vary: 'Accept-Encoding' } ]
> npm verb get saving twitter_cldr to /root/.npm/registry.npmjs.org/twitter_cldr/.cache.json
> npm verb correctMkdir /root/.npm correctMkdir not in flight; initializing
> npm verb makeDirectory /root/.npm creation not in flight; initializing
> npm sill makeDirectory /root/.npm uid: 0 gid: 0
> npm sill resolveWithNewModule twitter_cldr@2.1.0 checking installable status
> npm sill cache add args [ 'twitter_cldr@^2.1.0', null ]
> npm verb cache add spec twitter_cldr@^2.1.0
> npm sill cache add parsed spec Result {
> npm sill cache add   raw: 'twitter_cldr@^2.1.0',
> npm sill cache add   scope: null,
> npm sill cache add   name: 'twitter_cldr',
> npm sill cache add   rawSpec: '^2.1.0',
> npm sill cache add   spec: '>=2.1.0 <3.0.0',
> npm sill cache add   type: 'range' }
> npm sill addNamed twitter_cldr@>=2.1.0 <3.0.0
> npm verb addNamed ">=2.1.0 <3.0.0" is a valid semver range for twitter_cldr
> npm sill addNameRange { name: 'twitter_cldr', range: '>=2.1.0 <3.0.0', hasData: false }
> npm sill mapToRegistry name twitter_cldr
> npm sill mapToRegistry using default registry
> npm sill mapToRegistry registry https://registry.npmjs.org/
> npm sill mapToRegistry uri https://registry.npmjs.org/twitter_cldr
> npm verb addNameRange registry:https://registry.npmjs.org/twitter_cldr not in flight; fetching
> npm verb get https://registry.npmjs.org/twitter_cldr not expired, no request
> npm sill addNameRange number 2 { name: 'twitter_cldr', range: '>=2.1.0 <3.0.0', hasData: true }
> npm sill addNameRange versions [ 'twitter_cldr',
> npm sill addNameRange   [ '1.0.0',
> npm sill addNameRange     '1.1.0',
> npm sill addNameRange     '1.2.0',
> npm sill addNameRange     '1.3.0',
> npm sill addNameRange     '1.3.1',
> npm sill addNameRange     '1.3.2',
> npm sill addNameRange     '1.3.3',
> npm sill addNameRange     '1.3.4',
> npm sill addNameRange     '1.3.5',
> npm sill addNameRange     '2.0.0',
> npm sill addNameRange     '1.4.0',
> npm sill addNameRange     '1.5.0',
> npm sill addNameRange     '1.3.6',
> npm sill addNameRange     '2.1.0' ] ]
> npm sill addNamed twitter_cldr@2.1.0
> npm verb addNamed "2.1.0" is a plain semver version for twitter_cldr
> npm sill mapToRegistry name twitter_cldr
> npm sill mapToRegistry using default registry
> npm sill mapToRegistry registry https://registry.npmjs.org/
> npm sill mapToRegistry uri https://registry.npmjs.org/twitter_cldr
> npm verb addRemoteTarball https://registry.npmjs.org/twitter_cldr/-/twitter_cldr-2.1.0.tgz not in flight; adding
> npm verb addRemoteTarball [ 'https://registry.npmjs.org/twitter_cldr/-/twitter_cldr-2.1.0.tgz',
> npm verb addRemoteTarball   '89eba581b0b97b32ff4b7e2ef94fbbd0fba6abec' ]
> npm info retry fetch attempt 1 at 3:12:11 PM
> npm info attempt registry request try #1 at 3:12:11 PM
> npm http fetch GET https://registry.npmjs.org/twitter_cldr/-/twitter_cldr-2.1.0.tgz
> npm http fetch 200 https://registry.npmjs.org/twitter_cldr/-/twitter_cldr-2.1.0.tgz
> npm sill fetchAndShaCheck shasum 89eba581b0b97b32ff4b7e2ef94fbbd0fba6abec
> npm verb addTmpTarball /tmp/npm-60-a52eb88a/registry.npmjs.org/twitter_cldr/-/twitter_cldr-2.1.0.tgz not in flight; adding
> npm verb addTmpTarball already have metadata; skipping unpack for twitter_cldr@2.1.0
> npm verb correctMkdir /root/.npm correctMkdir not in flight; initializing
> npm sill cache afterAdd twitter_cldr@2.1.0
> npm verb afterAdd /root/.npm/twitter_cldr/2.1.0/package/package.json not in flight; writing
> npm verb correctMkdir /root/.npm correctMkdir not in flight; initializing
> npm verb afterAdd /root/.npm/twitter_cldr/2.1.0/package/package.json written
> npm ERR! cb() never called!
> 
> ERROR: Build failed: exit code 1

in other environment all is fine (npm: 3.6.0, node: v5.6.0; npm: 3.8.6, node: v6.1.0)

**Comment by andrew-gardener** [comment]
Travis CI is much more stable with the changes in #367. 

We no longer need to limit the amount of Travis CI jobs now since the unit tests no longer needlessly connect to saucelabs (open and closing several unused connections seems to have been part of the instability in the Travis tests)

I think the stability is good enough now to close this.

**Comment by xcompass** [comment]
👍 good job
