### ISSUE TITLE
Allow group creation from course user management screen

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#282]
Always include groups column and put a way to add groups on this page. Dependent on #266.

**Comment by andrew-gardener** [comment]
@lenglund For adding users to non-existing groups, how about adding a checkbox for every row and then some multi-edit actions at the bottom(/top?) of the table. 

Actions could be:
- drop all selected users from course
- add all selected users to existing group (with a group select list)
- add all selected users to new group (with modal asking for group name)
- change all selected users' course role (with a course role select list) *might be less useful

**Comment by lenglund** [comment]
Great idea. We could potentially do away with the assign groups button/workflow entirely.

**Comment by lenglund** [comment]
Want to:
- [ ] Remove assign groups button

**Comment by lenglund** [comment]
Can we change the error message when no users have been selected and any action is initiated so instead of saying "Must have at least one user id" it says "Please select at least one user below"?

**Comment by andrew-gardener** [comment]
@lenglund updated error messages in https://github.com/ubc/acj-versus/commit/c26e224470ae9770ff094e4c608bf1b788757252

**Comment by lenglund** [comment]
Two more requests for @andrew-gardener:
- [ ] Keep groups temporarily in the "existing groups" dropdown even if the user removes all users from this group (allows user to undo a mistake in group assignment), at least until user leaves the page
- [ ] Don't allow logged in user to update course role when using the bulk action to do so - instead, all other users should be updated but this user's course role should remain unchanged

**Comment by andrew-gardener** [comment]
Leaving open to test Github auto-close issues

**Comment by andrew-gardener** [comment]
Git auto-close issue didn't work

**Comment by xcompass** [comment]
I think it might be because we don't have one of those keywords in the commit message:
https://help.github.com/articles/closing-issues-via-commit-messages/
