### ISSUE TITLE
Force Gravatar Anonymity

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/acj-versus#285]
We might want to consider forcing default avatars using parameter `f=y`

If a student sets up their Gravatar account and uploads a photo of themselves they could lose their anonymity quite easily.

**Comment by xcompass** [comment]
Good catch. Agreed.

**Comment by lenglund** [comment]
Instructional text will need to be updated on the profile page once this change is implemented.

**Comment by andrew-gardener** [comment]
We could force default avatars for students only while instructors can still use their Gravatar profile images. Does this sound good or should we force defaults on everyone?

**Comment by lenglund** [comment]
Sounds good to me.

**Comment by andrew-gardener** [comment]
Leaving open to see if GitHub auto-closes the issue

**Comment by lenglund** [comment]
Finished in 99462e9925d76ddcfce589c60faeb4539187814a.
