### ISSUE TITLE
UI Updates

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#289]
- [x] Everywhere: Compair -> ComPAIR (#295)
- [x] Assignments: Set discuss to unselected by default; Match self-reflection/evaluation term with heading used; Show total number of comparisons based on your current selection
- [x] Comparisons: Switch comparison steps, so feedback comes second; Improve text editor appearance for feedback (simplify?); Remove rationale input for comparisons
- [x] Comparison View: Remove comparison rationale (no longer going to be used)
- [x] Question: Add public or private icon for feedback; Improve scannability of student's work tab; Remove comparison rationale for student's work tab (no longer going to be used)
- [x] Reply: Add public/private indicators

**Comment by andrew-gardener** [comment]
Since we're removing the comments for each criteria in comparisons from the UI, can we also remove it from the DB or do we want to leave it for potential future use?

**Comment by lenglund** [comment]
Hmm, the alternative approach to the comparisons is to leave feedback per criterion. Could these fields be re-used for that purpose, if we decide to go that route instead? If so, I'd leave them for now, since we've not yet piloted the new approach...

**Comment by lenglund** [comment]
Completed in 8ddee0ef8e3e365ba92c728f5afe8cdd10f94f11.
