### ISSUE TITLE
Option to choose pair selection algorithm

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/acj-versus#315]
Based on discussions with Ido and instructors, the pair selection algorithm should be random by default to promote fairness for students who perform their comparisons later on.  

- [x] Add new random pair selection algorithm (#321)
- [x] Update database to store pair algorithm in assignment table (#321)
- [x] Update assignment form UI to include radio buttons for selecting pair algorithm (default random) in new advanced section
- [x] Hide Rank/Score from UI when random selection is used

<s>Question:</s>
- <s>Should the algorithm selection be at the assignment or course level?</s> *assignment level chosen

**Comment by lenglund** [comment]
Let's do course level. I'd probably put this in an "advanced" fieldset and would prefer a radio button choice (e.g., between default "Linear (similar experience for all students)" and "Adaptive (increased challenge for later students)" or something similar) with instructional text to elaborate on the difference.

**Comment by xcompass** [comment]
Does it mean instructor can only use one algo in each course?

**Comment by lenglund** [comment]
Yes.

**Comment by xcompass** [comment]
Why not on assignment level?

**Comment by lenglund** [comment]
As discussed in the meeting today, it is an advanced/complicated feature that the majority of instructors will not likely use. Based on the workshop feedback especially, it seems that most instructors will leave this defaulted anyway.

**Comment by lenglund** [comment]
Are we considering the score itself to be meaningless when random is used? That is, should the answers scores be hidden from instructors in this case? Or do we only want to hide rank from students?

**Comment by xcompass** [comment]
I think hiding both make sense, since it's meaningless for both instructor and student.

**Comment by lenglund** [comment]
Completed in 298aa93eeb3cfeab435749ac92a6b0deef800dec.
