### ISSUE TITLE
LTI UI Elements

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#337]
- [x] Login Screen: "Welcome to ComPAIR" wording change to heading; "Or use a ComPAIR account"" wording change and change to h3 heading; Add option for create an account, conditionally displayed only for LTI links
- [x] Assignments Form: Include conditionally-displayed LTI custom parameter as non-editable text in assignment area with option to copy
- [x] Add User: Option only available to admins; Rename to "Create Account"; Divide into "Account Details" and "Account Login"; First section includes display name, first name, last name, student number, email; Second section includes instructional text, ComPAIR username, ComPAIR password, verify password
- [x] Edit User: Updates to match notes above (with additional work needed in #335)
- [x] Manage Users: Remove inline enrolment for non-admins; Add conditional Refresh button, pending enrolment message displayed only for LTI courses; Update instructional text
- [x] List of issues noted below

Ties to #263.

**Comment by lenglund** [comment]
![choose-course-option](https://cloud.githubusercontent.com/assets/6118592/17411522/83d68a74-5a2d-11e6-8503-250a9df960c5.png)
![create-account](https://cloud.githubusercontent.com/assets/6118592/17411521/83d684f2-5a2d-11e6-8338-3834830cda9e.png)
![lti-info](https://cloud.githubusercontent.com/assets/6118592/17411524/83dac86e-5a2d-11e6-8c4d-162ad6b5b0b5.png)
![manage-users](https://cloud.githubusercontent.com/assets/6118592/17411523/83d9ce5a-5a2d-11e6-8195-cfbd479409b5.png)
![new-login](https://cloud.githubusercontent.com/assets/6118592/17411525/83dc9428-5a2d-11e6-99f4-b53f323d9d15.png)

**Comment by lenglund** [comment]
Issues to address:
- [ ] Password is pre-populated for ComPAIR login and shouldn't be
- [ ] No course role given for instructor in the course (at least not visible in UI)
- [ ] Username should be editable by user now (added to form but not yet working)
- [ ] Instructor should not see student number field for own profile

Questions:
1) What is the plan for handling situations where multiple courses are found? How many do we show and do we then offer option to load more or pagination or...?
2) I ran into issues doing the duplication, but I'm not sure if it was my setup or a larger issue. When I did try to duplicate, I saw an error message but the course did duplicate...

**Comment by andrew-gardener** [comment]
> 1) What is the plan for handling situations where multiple courses are found? How many do we show and do we then offer option to load more or pagination or...?
I think pagination (~5 per page) would be good. We should also add pagination to the home pages as well while we're at it.

> 2) I ran into issues doing the duplication, but I'm not sure if it was my setup or a larger issue. When I did try to duplicate, I saw an error message but the course did duplicate...
I'll need to look into again (it worked for we without an error). I didn't fully complete the duplicate feature though since we moved it to 0.9.1 (doesn't handle assignment answer/compare dates, etc yet). I'll likely just hide the button for now.

**Comment by lenglund** [comment]
Other than the minor tweak to student profiles in the PR, looks good to me. Thanks!
