### ISSUE TITLE
Allow instructors to mark approval/disapproval for answer ranking and/or questions.

### ISSUE THREAD

**Issue by ionparticle** [ubc/acj-versus#50]
If the instructor finds that students have created poor quality questions or unwittingly ranked low quality answers as high, they should have a mechanism to indicate their disapproval. Conversely, they should also have a way of indicating approval for high quality questions/answers.

This could also be a good way for students to easily sort out high quality/high effort questions/answers.

**Comment by lenglund** [comment]
Seems to duplicate #201.
