### ISSUE TITLE
Answers list should visually group equal score answers somehow

### ISSUE THREAD

**Issue by ionparticle** [ubc/acj-versus#51]
To prevent the impression that equal scored answers might have a ranking within each other, maybe something should be done to visually denote a whole section of equal score answers as having the same rank.

**Comment by lenglund** [comment]
Can we assume our description of the scores will be enough to overcome this potential confusion?

**Comment by ionparticle** [comment]
Are those scores visible to students now? At the time when this suggestion was made, it's cause students don't have the score information, so they have no way of knowing if answers have equal scores.

**Comment by lenglund** [comment]
Students are not supposed to know scores, only see a relative ranking. So this would only apply to instructors/TAs.

**Comment by ionparticle** [comment]
Sorry, I need to clarify that this suggestion was made in regards to the student's view of the relative ranking. The concern is that, if a student sees a list of 3 answers, they're going to assume that the top answer is higher quality and the bottom answer is lower quality. But it could happen that, in actuality, those 3 answers have the same score and should actually be equivalent quality. There needs to be some indication of that.

**Comment by lenglund** [comment]
Since instructors don't want scores/rankings clearly displayed, indications of what answers scored the same may not be preferable either.

**Comment by lenglund** [comment]
This would clarify some confusion for students trying to figure out why the top answers are the top answers, an issue brought up in the focus groups.

**Comment by lenglund** [comment]
Because the larger groups end up with so many similarly-ranked answers, the need for this clarity is increased, provided it is something instructors want.

**Comment by lenglund** [comment]
Needs decision of issue #237 first.

**Comment by lenglund** [comment]
Possible resolution:
- [ ] Add rank number to top xx% answers and indicate "Tied" when applicable?

**Comment by lenglund** [comment]
Requires additional new API to retrieve all scores.

**Comment by lenglund** [comment]
Code ready for API in 4f9daf014c274abfe7412c8bf235de19319a3033.

**Comment by andrew-gardener** [comment]
#298 Instead of adding a new API endpoint for scores, I instead modified the score data returned from the answers API to include score rank for restricted users (students). This also allows only instructors and teaching assistants to see the normalized score though the API.

**Comment by lenglund** [comment]
Work to be tracked and completed as part of #237.
