### ISSUE TITLE
Add/Edit Answer Screen: Provide warning when answer truncated

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#85]
Vitaly brought up the point that someone may submit an overly-long answer (e.g., an essay) that is truncated upon saving. Since the field has a limit (even though it is high--47,817), can we either prevent the user from being able to enter over the limit or provide a warning before saving so the user can edit the answer first?

**Comment by mwytang** [comment]
Works for me: I've tried entering 52773 characters, and nothing is truncated.
