### ISSUE TITLE
Add/Edit Answer Screen: Need better handling of answering period cut-off time

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#87]
Vitaly notes that students who are in the middle of writing or editing an answer when the answer submission deadline passes are not allowed to submit the answer (or save changes to the answer). The error message is also unclear here, as it says simply "You do not have the required permissions" when trying to save.

I think it is preferable to allow students to submit/save their work, at least for a grace period a little after the cut-off time. (Ideally, the form would auto-save along the way.) If this is not possible, the error message needs to change to reflect what has happened, e.g., "The end of the answering period has passed."

**Comment by mwytang** [comment]
We may be able to create the auto-submit feature with $interval (https://docs.angularjs.org/api/ng/service/$interval)

**Comment by mwytang** [comment]
implemented for answer submissions in commit e71b8eb8268bc263850c8e00cf648a3a95899dea.

**Comment by mwytang** [comment]
The countdown timer is currently placed right above the ckeditor in answer-form-partial.html. @lenglund probably need to refactor its look a bit.

**Comment by lenglund** [comment]
Updates made in 695da4f70bffe8645a832711fa3bd1fc2cfb74e1

**Comment by mwytang** [comment]
- Remove the redirect if answer period is over.
- Look over the error message wording
