### ISSUE TITLE
IE 9

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#89]
Having trouble accessing the application using IE 9.

**Comment by mwytang** [comment]
I don't remember what the problem was exactly, but I can login into the system now. However I have a problem with logging out. Whether I'm logged in with my CWL or internal login credentials, I have to select logout twice. Even when I have successfully logged out, the interface does not clear the information and buttons on the page unlike Firefox, Chrome, and Safari.

**Comment by mwytang** [comment]
There has been reports of students not being redirected after a successful submission of evaluation. They were using IE.

**Comment by lenglund** [comment]
Issues with IE9 likely related to 197.

**Comment by lenglund** [comment]
Main issues with IE9 resolved with https://github.com/ubc/acj-versus/commit/0b951a1fb3bc9de5dc030b027aee2beec152b937. I will open a new ticket with the two specific, smaller issues remaining.
